# Site settings
title: L's Thought Hub
SEOTitle: Lorne的博客 | BY Lorne
header-img: img/post-bg-desk.jpg
email: zgl27375885@gmail.com
description: "Unity of knowledge and action."
keyword: "BY, BY Lorne, 汁的博客, zhugezhi, 诸葛汁, Photo, Lit, Math"
url: "http://zhugezhi.github.io"          # your host, for absolute URL
baseurl: "/"      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/ZhuGezhi/zhugezhi.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Knowledge and action unite; action validates knowledge."
sidebar-avatar: /img/about-LZ-gentle.JPG      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: true
weibo_username:     Lorne7711
zhihu_username:     卤汁香.
github_username:    ZhuGezhi
twitter_username:   zgl27375885




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: flalse    #是否开启Gitalk评论
  clientID: Ov23liEeAkAaaPBsp5G0                           #生成的clientID
  clientSecret: f04fdd477c4baab8088a20848fc07ecf37630793    #生成的clientSecret
  repo: blog-comments    #仓库名称
  owner: ZhuGezhi    #github用户名
  admin: ZhuGezhi
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'G-CZXSW9B3FH'            # Format: UA-xxxxxx-xx
ga_domain: zhugezhi.icu               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "抖音",
        href: "https://www.douyin.com/"
    },{
        title: "小红书",
        href: "https://www.xiaohongshu.com/"
    },{
        title: "GitHub",
        href: "https://github.com/"
    }
]
