# Site settings
title: "L's Thought Hub"
SEOTitle: "Lorne的博客 | BY Lorne"
header-img: "img/post-bg-desk.jpg"
email: "zgl27375885@gmail.com"
description: "Unity of knowledge and action."
keyword: "BY, BY Lorne, 汁的博客, zhugezhi, 诸葛汁, Photo, Lit, Math"
url: "https://zhugezhi.github.io"
baseurl: "/"
github_repo: "https://github.com/ZhuGezhi/zhugezhi.github.io.git"

# Sidebar settings
sidebar: true
sidebar-about-description: "Knowledge and action unite; action validates knowledge."
sidebar-avatar: "/img/about-LZ-gentle.jpg"

# SNS settings
RSS: false
weibo_username: "Lorne7711"
zhihu_username: "卤汁香."
github_username: "ZhuGezhi"
twitter_username: "zgl27375885"

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

# Gems
plugins: 
  - jekyll-paginate
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 评论系统
gitalk:
  enable: false
  clientID: "Ov23liEeAkAaaPBsp5G0"
  clientSecret: "f04fdd477c4baab8088a20848fc07ecf37630793"
  repo: "blog-comments"
  owner: "ZhuGezhi"
  admin: ["ZhuGezhi"]
  distractionFreeMode: true

# 统计
ga_track_id: "G-CZXSW9B3FH"
ga_domain: "zhugezhi.icu"

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#4299e1"
service-worker: true

# Friends
friends: [
    {
        title: "抖音",
        href: "https://www.douyin.com/"
    },{
        title: "小红书",
        href: "https://www.xiaohongshu.com/"
    },{
        title: "GitHub",
        href: "https://github.com/"
    }
]

# 额外配置
timezone: Asia/Shanghai
encoding: utf-8

# 默认布局配置
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
